name: Build GKI

on:
  workflow_call:
    inputs:
      KERNEL_NAME:
        type: string
        required: true
      VARIANT:
        type: string
        required: true
      SCHED_HZ:
        type: string
        required: true

  workflow_dispatch:
    inputs:
      kernel_name:
        description: 'Kernel Name'
        required: false
        default: 'zixine-elysium'
        type: string
      variant:
        description: 'Variant'
        required: true
        type: choice
        default: 'KSU'
        options:
          - 'KSU'
          - 'KSUS'
          - 'VNL'
      scheduler_hz:
        description: 'Kernel tickrates'
        required: true
        type: choice
        default: '250HZ'
        options:
          - '100HZ'
          - '250HZ'
          - '300HZ'
          - '500HZ'
          - '750HZ'
          - '1000HZ'

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ inputs.KERNEL_NAME }}-${{ inputs.VARIANT }}
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "zixine"
          git config --global user.email "waheiiiddd@gmail.com"

      - name: Init & Sync GKI
        run: |
          # Install repo tool
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          export PATH="$HOME/bin:$PATH"

          mkdir gki && cd gki
          repo init -u https://android.googlesource.com/kernel/manifest -b common-android12-5.10 --depth=1
          repo sync -c --no-tags --no-clone-bundle --optimized-fetch -j$(nproc --all)

      - name: Setup Kernel Source
        run: |
          cd gki/common
          git remote add waheiiiddd-lab https://github.com/ramabondanp/android_kernel_common-5.10.git
          git fetch -j12 waheiiiddd-lab
          git checkout -b update-android-12.5.20-staging waheiiiddd-lab/lts
          rm -rf drivers/staging/kernelsu
      
      - name: Naga Patch
        run: |
          cd gki/common
          TARGET="drivers/cpufreq/qcom-cpufreq-hw.c"
          SRC_URL="https://raw.githubusercontent.com/Pzqqt/android_kernel_xiaomi_marble/refs/heads/melt-rebase/drivers/cpufreq/qcom-cpufreq-hw.c"
          curl -L "$SRC_URL" -o /tmp/qcom-cpufreq-hw.c
          cp /tmp/qcom-cpufreq-hw.c "$TARGET"

      - name: Setup Variant
        working-directory: gki/common
        run: |
          DEFCONFIG="arch/arm64/configs/gki_defconfig"
          VARIANT="${{ inputs.VARIANT }}"
          
          sed -i '/CONFIG_KSU/d' $DEFCONFIG
          sed -i '/CONFIG_KSU_SUSFS/d' $DEFCONFIG

          if [ "$VARIANT" == "KSU" ]; then
            curl -LSs "https://raw.githubusercontent.com/pershoot/kernelSU-Next/dev-susfs/kernel/setup.sh" | bash -s dev-susfs
            echo "CONFIG_KSU=y" >> $DEFCONFIG
            echo "# CONFIG_KSU_SUSFS is not set" >> $DEFCONFIG
            echo "ENABLE_SUSFS=false" >> $GITHUB_ENV
            
            echo "Patch All Managers Support..."
            curl -LSs "https://raw.githubusercontent.com/Kingfinik98/gki-builder/refs/heads/6.x/kernel-patches/ksu/ksun-add-more-managers-support.patch" -o /tmp/ksun-add-more-managers-support.patch
            cd KernelSU-Next && patch -p1 < /tmp/ksun-add-more-managers-support.patch && cd ..

          elif [ "$VARIANT" == "KSUS" ]; then
            curl -LSs "https://raw.githubusercontent.com/pershoot/kernelSU-Next/dev-susfs/kernel/setup.sh" | bash -s dev-susfs
            git clone https://gitlab.com/simonpunk/susfs4ksu/ -b gki-android12-5.10 sus
            rm -rf sus/.git
            susfs=sus/kernel_patches
            cp -r $susfs/fs . && cp -r $susfs/include .
            cp -r $susfs/50_add_susfs_in_gki-android12-5.10.patch .
            patch -p1 < 50_add_susfs_in_gki-android12-5.10.patch

            echo "CONFIG_KSU=y" >> $DEFCONFIG
            echo "CONFIG_KSU_SUSFS=y" >> $DEFCONFIG
            if [ -f "drivers/kernelsu/supercalls.c" ]; then
              sed -i 's/#ifdef CONFIG_KSU_SUSFS_SPOOF_UNAME/#if 0 \/\* CONFIG_KSU_SUSFS_SPOOF_UNAME Disabled to fix build \*\//' drivers/kernelsu/supercalls.c || true
              echo "SUSFS symbol fix applied for KernelSU-Next."
            else
              echo "Skipping obsolete SUSFS uname fix."
            fi
            echo "ENABLE_SUSFS=true" >> $GITHUB_ENV
            
            echo "Patch All Managers Support..."
            curl -LSs "https://raw.githubusercontent.com/Kingfinik98/gki-builder/refs/heads/6.x/kernel-patches/ksu/ksun-add-more-managers-support.patch" -o /tmp/ksun-add-more-managers-support.patch
            cd KernelSU-Next && patch -p1 < /tmp/ksun-add-more-managers-support.patch && cd ..

          else
            echo "ENABLE_SUSFS=false" >> $GITHUB_ENV
          fi
          
          sed -i '/CONFIG_HZ=/d' $DEFCONFIG
          cat <<EOF >> $DEFCONFIG
          CONFIG_HZ=$(echo "${{ inputs.SCHED_HZ }}" | sed 's/HZ//')
          CONFIG_EXT4_FS=y
          CONFIG_EXT4_FS_POSIX_ACL=y
          CONFIG_EXT4_FS_SECURITY=y
          CONFIG_ZRAM=y
          CONFIG_DEFAULT_BBR=y
          CONFIG_DEFAULT_TCP_CONG="bbr"
          CONFIG_TMPFS_POSIX_ACL=y
          CONFIG_IP6_NF_TARGET_HL=y
          CONFIG_IP6_NF_MATCH_HL=y
          CONFIG_CPU_FREQ_GOV_ZIXINE_VELOCITY=y
          CONFIG_CPU_FREQ_STAT=y
          CONFIG_CPU_FREQ_TIMES=y
          CONFIG_NO_HZ_IDLE=y
          CONFIG_WQ_POWER_EFFICIENT_DEFAULT=y
          CONFIG_CPU_IDLE=y
          # CONFIG_PROVE_LOCKING is not set
          # CONFIG_DEBUG_KMEMLEAK is not set
          CONFIG_UCLAMP_TASK=y
          CONFIG_NTSYNC=y
          CONFIG_ENERGY_MODEL=y
          CONFIG_JUMP_LABEL=y
          EOF
      
      - name: Patch DRM Xiaomi
        working-directory: gki/common
        run: |
          sed -i '/config STACKPROTECTOR_PER_TASK/{n;s/def_bool y/bool "Stack Protector per task"\n\tdefault y/;}' arch/arm64/Kconfig
          sed -i '/pr_warn.*disagrees about version of symbol.*/,+1 s/.*/return 1;/' kernel/module.c
          sed -i '/^static int drm_atomic_check_valid_clones/,/^}/d' drivers/gpu/drm/drm_atomic_helper.c
          sed -i '/ret = drm_atomic_check_valid_clones/,/return ret;/d' drivers/gpu/drm/drm_atomic_helper.c
      
      - name: Remove check_defconfig
        run: |
          sed -i 's/check_defconfig//' gki/common/build.config.gki
      
      - name: Set version
        working-directory: gki/common
        run: |
          echo "" > scripts/setlocalversion
          chmod +x scripts/setlocalversion
          
          KERNEL_NAME_INPUT="${{ inputs.KERNEL_NAME }}"
          VARIANT="${{ inputs.VARIANT }}"
          SUFFIX=""
          if [ -n "$KERNEL_NAME_INPUT" ]; then
            SUFFIX="-$KERNEL_NAME_INPUT"
          fi
          if [ "$VARIANT" == "KSU" ]; then
            SUFFIX="$SUFFIX-KSU"
          elif [ "$VARIANT" == "KSUS" ]; then
            SUFFIX="$SUFFIX-HybridVelocity.3.7"
          elif [ "$VARIANT" == "VNL" ]; then
            SUFFIX="$SUFFIX-VNL"
          fi

          if grep -q '^EXTRAVERSION *=' Makefile; then
            sed -i "s/^EXTRAVERSION *=.*/EXTRAVERSION = $SUFFIX/" Makefile
          else
            echo "EXTRAVERSION = $SUFFIX" >> Makefile
          fi

      - name: Setup Toolchain
        working-directory: gki
        run: |
          mkdir -p prebuilts-master/clang/host/linux-x86
          CLANG_VER="clang-r416183b"
          CLANG_URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/master-kernel-build-2021/clang-r416183b.tar.gz"
          echo "CLANG_VER=$CLANG_VER" >> $GITHUB_ENV
          mkdir -p prebuilts-master/clang/host/linux-x86/$CLANG_VER
          cd prebuilts-master/clang/host/linux-x86
          curl -L "${CLANG_URL}" -o clang-temp.tar.gz
          tar -xzf clang-temp.tar.gz -C $CLANG_VER
          rm -f clang-temp.tar.gz
          rm -rf clang-r563880b
          ln -sf $CLANG_VER clang-r563880b
      
      - name: Commit changes
        working-directory: gki/common
        run: |
          git add .
          git commit -m "Final clean tree before build" || true

      - name: Compile
        working-directory: gki
        run: |
          # Ensure repo is in path for build scripts if needed
          export PATH="$HOME/bin:$PATH"
          export SKIP_ABI_CHECKS=1
          export UPDATE_SYMBOL_LIST=1
          export KMI_SYMBOL_LIST_STRICT_MODE=0
          export KBUILD_BUILD_USER="zixine"
          export KBUILD_BUILD_HOST="aitt"
          LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh -j$(nproc --all)

      - name: Package Kernel
        run: |
          mkdir -p artifacts
          VERSION=$(make -s kernelversion -C gki/common)
          BUILD_DATE=$(date +"%Y%m%d")
          BASE="AK3-${VERSION}-+${BUILD_DATE}"
          echo "BASE=$BASE" >> $GITHUB_ENV
          ZIP_NAME="${BASE}.zip"

          git clone -q --depth=1 https://github.com/waheiiiddd-lab/AnyKernel345 anykernel
          cp gki/out/android12-5.10/dist/Image anykernel/

          cd anykernel
          zip -r9 "../artifacts/$ZIP_NAME" ./*
          cd ..

          cat <<EOF > artifacts/info.txt
          KERNEL_NAME=$BASE
          KVER=$VERSION
          VARIANT=${{ inputs.VARIANT }}
          DATE=$BUILD_DATE
          EOF

      - name: Upload AnyKernel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BASE }}-${{ github.run_number }}
          path: artifacts/*.zip

      - name: Upload Info.txt artifact
        uses: actions/upload-artifact@v4
        with:
          name: info-${{ github.run_number }}
          path: artifacts/*.txt
          
